# Generated by Django 6.0.4 on 2026-04-26 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='cilindrada',
        ),
        migrations.AddField(
            model_name='moto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default='2026-04-26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='motos'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moto',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
